name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "siren.aot.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.siren.aot.biz.id", custom_domain = true },
  { pattern = "cache.netflix.com.siren.aot.biz.id", custom_domain = true },
  { pattern = "df.game.naver.com.siren.aot.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.siren.aot.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.siren.aot.biz.id", custom_domain = true },  
  { pattern = "quiz.int.vidio.com.siren.aot.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.siren.aot.biz.id", custom_domain = true },
  { pattern = "siren.aot.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.siren.aot.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.siren.aot.my.id", custom_domain = true },
  { pattern = "df.game.naver.com.siren.aot.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.siren.aot.my.id", custom_domain = true },
  { pattern = "support.zoom.us.siren.aot.my.id", custom_domain = true },  
  { pattern = "quiz.int.vidio.com.siren.aot.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.siren.aot.my.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "eeab9f856074466098927b4d9bbaf848"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "abababab-cdcd-4e4e-efef-fefefefefefe"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/p3np4y/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/p3np4y/Siren/refs/heads/master/web/sub.html"
